[dataset]
hdf5_file='LIVE_NFLX_PLUS/live_nflx_plus_frame.h5'
train_csv='Datasets/LIVE_NFLX_II/tbl_df/live_nflx_ii_video_train.csv'
test_csv='Datasets/LIVE_NFLX_II/tbl_df/live_nflx_ii_video_test.csv'
train_max_len=1069
test_max_len=963

[map]
tb_logger_dir="discovqa"
checkpoint_filename="discovqa"
checkpoint_dir="checkpoints"

[run]
batch_size=1
learning_rate=1e-3
epoch=50
weight_decay=1e-3
resolution=112
